/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ProofPayEscrowInterface extends Interface {
  getFunction(
    nameOrSignature: "coordinator" | "getJob" | "settleJob" | "submitJob"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "JobSettled" | "JobSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "coordinator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getJob", values: [string]): string;
  encodeFunctionData(
    functionFragment: "settleJob",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitJob",
    values: [string, AddressLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "coordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settleJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitJob", data: BytesLike): Result;
}

export namespace JobSettledEvent {
  export type InputTuple = [jobId: string, verified: boolean];
  export type OutputTuple = [jobId: string, verified: boolean];
  export interface OutputObject {
    jobId: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobSubmittedEvent {
  export type InputTuple = [
    jobId: string,
    submitter: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: string, submitter: string, amount: bigint];
  export interface OutputObject {
    jobId: string;
    submitter: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofPayEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ProofPayEscrow;
  waitForDeployment(): Promise<this>;

  interface: ProofPayEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  coordinator: TypedContractMethod<[], [string], "view">;

  getJob: TypedContractMethod<
    [jobId: string],
    [
      [string, bigint, string[], boolean] & {
        submitter: string;
        amount: bigint;
        operators: string[];
        settled: boolean;
      }
    ],
    "view"
  >;

  settleJob: TypedContractMethod<
    [jobId: string, verified: boolean],
    [void],
    "nonpayable"
  >;

  submitJob: TypedContractMethod<
    [jobId: string, operators: AddressLike[]],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "coordinator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: string],
    [
      [string, bigint, string[], boolean] & {
        submitter: string;
        amount: bigint;
        operators: string[];
        settled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "settleJob"
  ): TypedContractMethod<
    [jobId: string, verified: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitJob"
  ): TypedContractMethod<
    [jobId: string, operators: AddressLike[]],
    [void],
    "payable"
  >;

  getEvent(
    key: "JobSettled"
  ): TypedContractEvent<
    JobSettledEvent.InputTuple,
    JobSettledEvent.OutputTuple,
    JobSettledEvent.OutputObject
  >;
  getEvent(
    key: "JobSubmitted"
  ): TypedContractEvent<
    JobSubmittedEvent.InputTuple,
    JobSubmittedEvent.OutputTuple,
    JobSubmittedEvent.OutputObject
  >;

  filters: {
    "JobSettled(string,bool)": TypedContractEvent<
      JobSettledEvent.InputTuple,
      JobSettledEvent.OutputTuple,
      JobSettledEvent.OutputObject
    >;
    JobSettled: TypedContractEvent<
      JobSettledEvent.InputTuple,
      JobSettledEvent.OutputTuple,
      JobSettledEvent.OutputObject
    >;

    "JobSubmitted(string,address,uint256)": TypedContractEvent<
      JobSubmittedEvent.InputTuple,
      JobSubmittedEvent.OutputTuple,
      JobSubmittedEvent.OutputObject
    >;
    JobSubmitted: TypedContractEvent<
      JobSubmittedEvent.InputTuple,
      JobSubmittedEvent.OutputTuple,
      JobSubmittedEvent.OutputObject
    >;
  };
}
