function boxStyle(): React.CSSProperties {
  return {
    background: "#0f1730",
    border: "1px solid #1f2b55",
    borderRadius: 12,
    padding: 14,
    minHeight: 220
  };
}

export function ManifestPanel({
  manifest,
  shardsSummary
}: {
  manifest: unknown | null;
  shardsSummary: { shardId: string; shardHash: string }[] | null;
}) {
  return (
    <section style={boxStyle()}>
      <h2 style={{ margin: 0, fontSize: 16 }}>Manifest</h2>
      <p style={{ margin: "8px 0 10px", opacity: 0.75, fontSize: 13 }}>
        Generated by coordinator: shard IDs, shard hashes, model version, recomposition rule.
      </p>

      {shardsSummary ? (
        <div style={{ display: "grid", gap: 8, marginBottom: 10 }}>
          {shardsSummary.map((s) => (
            <div
              key={s.shardId}
              style={{
                display: "grid",
                gridTemplateColumns: "120px 1fr",
                gap: 8,
                alignItems: "baseline",
                background: "#0b0f1a",
                border: "1px solid #1f2b55",
                borderRadius: 10,
                padding: 10
              }}
            >
              <div style={{ opacity: 0.85 }}>{s.shardId}</div>
              <div style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: 12 }}>
                {s.shardHash}
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div style={{ opacity: 0.7, fontSize: 13 }}>Run a job to generate a manifest.</div>
      )}

      {manifest ? (
        <pre
          style={{
            margin: 0,
            background: "#0b0f1a",
            border: "1px solid #1f2b55",
            borderRadius: 10,
            padding: 10,
            overflow: "auto",
            maxHeight: 170,
            fontSize: 12
          }}
        >
          {JSON.stringify(manifest, null, 2)}
        </pre>
      ) : null}
    </section>
  );
}

